version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    container_name: cache
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - "./redis/redis1:/redis/data"
    ports:
      - 6379:6379
      
  backend:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: zport_backend
    environment:
      - REDIS_URL=redis
      - PORT=5000
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - redis